//! Built-in configuration templates from Go's internal/template/builtins.go.
use base64::{Engine as _, engine::general_purpose::STANDARD};
use std::collections::BTreeMap;
use std::fmt::Write as _;

/// Render resolved string values in Go's sorted map order. Custom Go templates
/// require their own interpreter and must be rejected by callers, not ignored.
pub fn render_builtin(
    kind: &str,
    name: &str,
    values: &BTreeMap<String, String>,
) -> Result<String, String> {
    let mut output = match kind {
        "env" => "# Generated by Symaira Vault".to_owned(),
        "docker-compose" => "version: \"3.8\"\nservices:\n  app:\n    environment:".to_owned(),
        "k8s-secret" => {
            format!("apiVersion: v1\nkind: Secret\nmetadata:\n  name: {name}\ntype: Opaque\ndata:")
        }
        "github-actions" => format!(
            "name: Deploy {name}\n\non:\n  push:\n    branches: [main]\n\njobs:\n  deploy:\n    runs-on: ubuntu-latest\n    steps:\n      - uses: actions/checkout@v4\n      - name: Configure secrets\n        env:"
        ),
        "terraform" => format!("# Terraform variables for {name}\n# Generated by Symaira Vault"),
        _ => return Err(format!("template not found: {kind}")),
    };
    for (key, value) in values {
        match kind {
            "env" => {
                let _ = write!(output, "\nexport {key}={value}");
            }
            "docker-compose" => {
                let _ = write!(output, "\n      - {key}={value}");
            }
            "k8s-secret" => {
                let _ = write!(output, "\n  {key}: {}", STANDARD.encode(value));
            }
            "github-actions" => {
                let _ = write!(output, "\n          {key}: {value}");
            }
            "terraform" => {
                let encoded =
                    symvault_gojson::to_string(value).map_err(|error| error.to_string())?;
                let _ = write!(
                    output,
                    "\nvariable \"{}\" {{\n  type      = string\n  sensitive = true\n  default   = {encoded}\n}}",
                    symvault_core::go_to_lower(key)
                );
            }
            _ => unreachable!(),
        }
    }
    if kind == "docker-compose" {
        output.push_str("\n    secrets:");
        for key in values.keys() {
            let _ = write!(
                output,
                "\n      - {}_secret",
                symvault_core::go_to_lower(key)
            );
        }
        output.push_str("\nsecrets:");
        for key in values.keys() {
            let key = symvault_core::go_to_lower(key);
            let _ = write!(output, "\n  {key}_secret:\n    file: ./secrets/{key}.txt");
        }
    } else if kind == "github-actions" {
        output.push_str("\n        run: |\n          echo \"Secrets configured\"");
    }
    output.push('\n');
    Ok(output)
}
