package vault

import (
	"bytes"
	"errors"
	"os"
	"path/filepath"
	"reflect"
	"runtime"
	"sort"
	"testing"

	vaultconfig "github.com/danieljustus/symaira-vault/internal/config"
	"github.com/danieljustus/symaira-vault/internal/testutil"
)

// The production oracle is loadFromDisk in this checkout (initial revision
// e78db834c31195b600684db3e31a137eb5fd013c). Inputs are generated by Init,
// WriteEntry and Build; no index document or expected output is hand-written.
func TestEncryptedIndexListErrorOracle(t *testing.T) {
	testEncryptedIndexListError(t, false)
}

func TestEncryptedIndexListErrorGoRust(t *testing.T) {
	testEncryptedIndexListError(t, true)
}

func testEncryptedIndexListError(t *testing.T, differential bool) {
	t.Helper()
	if runtime.GOOS == "windows" {
		t.Skip("Unix directory permissions; native Windows failure injection remains open")
	}
	adapter := ""
	if differential {
		adapter = searchIndexAdapter(t)
	}
	root := t.TempDir()
	identity := testutil.TempIdentity(t)
	cfg := vaultconfig.Default()
	cfg.VaultDir = root
	if err := Init(root, identity, cfg); err != nil {
		t.Fatal(err)
	}
	mustWriteEntry(t, root, identity, "doc", map[string]any{"value": "Synthetic Marker"})
	FlushManifestUpdates()
	seed := &EncryptedIndex{}
	if err := seed.Build(root, identity); err != nil {
		t.Fatal(err)
	}
	prior, err := os.ReadFile(indexFilePath(root))
	if err != nil {
		t.Fatal(err)
	}
	// Force the production List fallback to walk entries rather than using its
	// manifest or cached paths. The encrypted index itself remains valid.
	if err := os.Remove(filepath.Join(root, manifestFileName)); err != nil {
		t.Fatal(err)
	}
	listCacheFor(root).Invalidate()
	before := indexBuildTree(t, root)
	entries := entriesDir(root)
	info, err := os.Stat(entries)
	if err != nil {
		t.Fatal(err)
	}
	t.Cleanup(func() {
		if err := os.Chmod(entries, info.Mode().Perm()); err != nil {
			t.Error(err)
		}
	})
	if err := os.Chmod(entries, 0); err != nil {
		t.Fatal(err)
	}
	idx := &EncryptedIndex{}
	loadErr := idx.loadFromDisk(root, identity)
	if err := os.Chmod(entries, info.Mode().Perm()); err != nil {
		t.Fatal(err)
	}
	if !errors.Is(loadErr, os.ErrPermission) {
		t.Fatalf("freshness check did not encounter the required permission failure: %v", loadErr)
	}
	_, statErr := os.Stat(indexFilePath(root))
	retry := &EncryptedIndex{}
	if err := retry.loadFromDisk(root, identity); err != nil {
		t.Fatal(err)
	}
	want := map[string]any{
		"permission_error": errors.Is(loadErr, os.ErrPermission),
		"index_removed":    errors.Is(statErr, os.ErrNotExist),
		"retry_absent":     !retry.IsBuilt(),
	}
	if idx.IsBuilt() || want["index_removed"] != true || want["retry_absent"] != true {
		t.Fatalf("Go accepted or retained an unverifiable index: %v", want)
	}
	if err := retry.Build(root, identity); err != nil {
		t.Fatal(err)
	}
	matches, err := retry.MatchEntries(root, identity, []string{"doc"}, "MARKER")
	if err != nil {
		t.Fatal(err)
	}
	if !reflect.DeepEqual(matches, map[string]struct{}{"doc": {}}) {
		t.Fatalf("Go rebuild did not recover search: %v", matches)
	}
	matchedPaths := make([]string, 0, len(matches))
	for path := range matches {
		matchedPaths = append(matchedPaths, path)
	}
	sort.Strings(matchedPaths)
	projectedMatches := make([]any, len(matchedPaths))
	for i, path := range matchedPaths {
		projectedMatches[i] = path
	}
	want["matches"] = projectedMatches
	if differential {
		if err := os.WriteFile(indexFilePath(root), prior, 0o600); err != nil {
			t.Fatal(err)
		}
		got := runSearchIndexAdapter(t, adapter, root, identity.String(), "load-list-error")
		if !reflect.DeepEqual(got, want) {
			t.Fatalf("Rust observation = %v; Go oracle = %v", got, want)
		}
	}
	if !reflect.DeepEqual(indexBuildTree(t, root), before) {
		t.Error("load/rebuild changed files or modes outside .search-index")
	}
	raw, err := os.ReadFile(indexFilePath(root))
	if err != nil {
		t.Fatal(err)
	}
	if bytes.Contains(raw, []byte("Synthetic Marker")) || bytes.Contains(raw, []byte("synthetic marker")) {
		t.Error("rebuilt index contains plaintext")
	}
}
