package vault

import (
	"bytes"
	"encoding/json"
	"errors"
	"os"
	"path/filepath"
	"reflect"
	"runtime"
	"sort"
	"testing"

	vaultconfig "github.com/danieljustus/symaira-vault/internal/config"
	"github.com/danieljustus/symaira-vault/internal/testutil"
)

// This live probe uses Init -> WriteEntry -> EncryptedIndex.Build and
// loadFromDisk/MatchEntries from the production Go oracle. The initial oracle
// revision is 9947991cda919d462fa6cdce2bf1a33d9716ff6b (Go 1.26.6).
// All encrypted inputs, including a pre-existing index, are generated by Go.
func TestEncryptedIndexBuildEmptyOracle(t *testing.T) {
	testEncryptedIndexBuildEmpty(t, "")
}

func TestEncryptedIndexBuildEmptyGoRust(t *testing.T) {
	testEncryptedIndexBuildEmpty(t, searchIndexAdapter(t))
}

type indexBuildObservation struct {
	Accepted               bool     `json:"accepted"`
	Error                  string   `json:"error"`
	Matches                []string `json:"matches"`
	LoadedMatches          []string `json:"loaded_matches"`
	CrossLineMatches       []string `json:"cross_line_matches"`
	LoadedCrossLineMatches []string `json:"loaded_cross_line_matches"`
	PaddedMatches          []string `json:"padded_matches"`
	LoadedPaddedMatches    []string `json:"loaded_padded_matches"`
}

func testEncryptedIndexBuildEmpty(t *testing.T, adapter string) {
	t.Helper()
	cases := []struct {
		name    string
		entries []map[string]any
		accept  bool
	}{
		{"empty_vault", nil, true},
		{"omitted_value", []map[string]any{{}}, false},
		{"explicit_null", []map[string]any{{"value": nil}}, false},
		{"empty_string", []map[string]any{{"value": ""}}, false},
		{"non_strings", []map[string]any{{"value": 42, "enabled": true}}, false},
		{"nested_empty", []map[string]any{{"value": []any{"", nil, map[string]any{"n": 42}}}}, false},
		{"nested_string", []map[string]any{{"value": []any{map[string]any{"text": "Synthetic Marker"}}}}, true},
		{"whitespace_string", []map[string]any{{"value": " "}}, true},
		{"backup_codes_whitespace", []map[string]any{{"backup_codes": " "}}, false},
		{"backup_codes_lines", []map[string]any{{"backup_codes": "first\nSynthetic Marker\n"}}, true},
		{"backup_codes_padded", []map[string]any{{"backup_codes": " first \nSynthetic Marker\n"}}, true},
		{"backup_codes_structured", []map[string]any{{"backup_codes": []any{"Synthetic Marker"}}}, true},
		{"nested_backup_codes", []map[string]any{{"nested": map[string]any{"backup_codes": " "}}}, true},
		{"mixed_entries", []map[string]any{{"value": 42}, {"value": "Synthetic Marker"}}, true},
	}
	for _, tc := range cases {
		for _, existing := range []bool{false, true} {
			name := tc.name + "/absent_index"
			if existing {
				name = tc.name + "/existing_index"
			}
			t.Run(name, func(t *testing.T) {
				root := t.TempDir()
				identity := testutil.TempIdentity(t)
				cfg := vaultconfig.Default()
				cfg.VaultDir = root
				if err := Init(root, identity, cfg); err != nil {
					t.Fatal(err)
				}
				var prior []byte
				if existing {
					seed := &EncryptedIndex{}
					if err := seed.Build(root, identity); err != nil {
						t.Fatal(err)
					}
					var err error
					prior, err = os.ReadFile(indexFilePath(root))
					if err != nil {
						t.Fatal(err)
					}
					seed.ClearMemory()
				}
				for i, data := range tc.entries {
					mustWriteEntry(t, root, identity, string(rune('a'+i)), data)
				}
				FlushManifestUpdates()
				restore := func() {
					t.Helper()
					if prior == nil {
						if err := os.Remove(indexFilePath(root)); err != nil && !errors.Is(err, os.ErrNotExist) {
							t.Fatal(err)
						}
					} else if err := os.WriteFile(indexFilePath(root), prior, 0o600); err != nil {
						t.Fatal(err)
					}
				}
				restore()
				before := indexBuildTree(t, root)
				paths, err := List(root, "", identity)
				if err != nil || len(paths) != len(tc.entries) {
					t.Fatalf("List = %v, %v", paths, err)
				}
				idx := &EncryptedIndex{}
				buildErr := idx.Build(root, identity)
				want := indexBuildObservation{Accepted: buildErr == nil}
				if buildErr != nil {
					want.Error = buildErr.Error()
					if !errors.Is(buildErr, ErrIndexBuildEmpty) {
						t.Fatalf("unexpected build rejection: %v", buildErr)
					}
				}
				if want.Accepted != tc.accept {
					t.Fatalf("Go accepted = %v, want %v", want.Accepted, tc.accept)
				}
				if want.Accepted {
					matches, err := idx.MatchEntries(root, identity, paths, "MARKER")
					if err != nil {
						t.Fatal(err)
					}
					want.Matches = make([]string, 0, len(matches))
					for path := range matches {
						want.Matches = append(want.Matches, path)
					}
					sort.Strings(want.Matches)
					loaded := &EncryptedIndex{}
					if err := loaded.loadFromDisk(root, identity); err != nil || !loaded.Covers(root, identity) {
						t.Fatalf("load built index: %v", err)
					}
					matches, err = loaded.MatchEntries(root, identity, paths, "MARKER")
					if err != nil {
						t.Fatal(err)
					}
					want.LoadedMatches = make([]string, 0, len(matches))
					for path := range matches {
						want.LoadedMatches = append(want.LoadedMatches, path)
					}
					sort.Strings(want.LoadedMatches)
					crossLine, err := idx.MatchEntries(root, identity, paths, "FIRST\nSYNTHETIC")
					if err != nil {
						t.Fatal(err)
					}
					want.CrossLineMatches = make([]string, 0, len(crossLine))
					for path := range crossLine {
						want.CrossLineMatches = append(want.CrossLineMatches, path)
					}
					sort.Strings(want.CrossLineMatches)
					crossLine, err = loaded.MatchEntries(root, identity, paths, "FIRST\nSYNTHETIC")
					if err != nil {
						t.Fatal(err)
					}
					want.LoadedCrossLineMatches = make([]string, 0, len(crossLine))
					for path := range crossLine {
						want.LoadedCrossLineMatches = append(want.LoadedCrossLineMatches, path)
					}
					sort.Strings(want.LoadedCrossLineMatches)
					padded, err := idx.MatchEntries(root, identity, paths, " FIRST ")
					if err != nil {
						t.Fatal(err)
					}
					want.PaddedMatches = make([]string, 0, len(padded))
					for path := range padded {
						want.PaddedMatches = append(want.PaddedMatches, path)
					}
					sort.Strings(want.PaddedMatches)
					padded, err = loaded.MatchEntries(root, identity, paths, " FIRST ")
					if err != nil {
						t.Fatal(err)
					}
					want.LoadedPaddedMatches = make([]string, 0, len(padded))
					for path := range padded {
						want.LoadedPaddedMatches = append(want.LoadedPaddedMatches, path)
					}
					sort.Strings(want.LoadedPaddedMatches)
				}
				checkIndexBuildSideEffects(t, root, before, prior, want.Accepted)
				raw, err := json.Marshal(want)
				if err != nil {
					t.Fatal(err)
				}
				t.Logf("Go observation: %s; index_exists=%v; prior_preserved=%v; other_files_unchanged=true", raw, want.Accepted || existing, !want.Accepted)
				if adapter != "" {
					restore()
					got := runSearchIndexAdapter(t, adapter, root, identity.String(), "build-observation")
					var expected map[string]any
					if err := json.Unmarshal(raw, &expected); err != nil {
						t.Fatal(err)
					}
					if !reflect.DeepEqual(got, expected) {
						t.Errorf("Rust observation = %v, Go = %v", got, expected)
					}
					checkIndexBuildSideEffects(t, root, before, prior, want.Accepted)
				}
			})
		}
	}
}

type indexBuildFile struct {
	Mode os.FileMode
	Data string
}

func indexBuildTree(t *testing.T, root string) map[string]indexBuildFile {
	t.Helper()
	result := make(map[string]indexBuildFile)
	err := filepath.Walk(root, func(path string, info os.FileInfo, err error) error {
		if err != nil {
			return err
		}
		name, err := filepath.Rel(root, path)
		if err != nil {
			return err
		}
		if name == ".search-index" {
			return nil
		}
		var data []byte
		if !info.IsDir() {
			data, err = os.ReadFile(path)
			if err != nil {
				return err
			}
		}
		result[name] = indexBuildFile{info.Mode(), string(data)}
		return nil
	})
	if err != nil {
		t.Fatal(err)
	}
	return result
}

func checkIndexBuildSideEffects(t *testing.T, root string, before map[string]indexBuildFile, prior []byte, accepted bool) {
	t.Helper()
	if !reflect.DeepEqual(indexBuildTree(t, root), before) {
		t.Error("build/load modified files or directories other than .search-index")
	}
	raw, err := os.ReadFile(indexFilePath(root))
	if !accepted && prior == nil {
		if !errors.Is(err, os.ErrNotExist) {
			t.Errorf("rejected build created an index: %v", err)
		}
		return
	}
	if err != nil {
		t.Fatal(err)
	}
	if !accepted && !bytes.Equal(raw, prior) {
		t.Error("rejected build changed the existing Go-produced index")
	}
	if accepted && (len(raw) <= 17 || raw[0] != indexFormatVersion || bytes.Equal(raw, prior)) {
		t.Error("accepted build did not publish a fresh salted index")
	}
	info, err := os.Stat(indexFilePath(root))
	if err != nil {
		t.Fatal(err)
	}
	wantMode := os.FileMode(0o600)
	if runtime.GOOS == "windows" {
		// Windows does not expose Unix permission bits; Go reports the
		// writable regular-file mode as 0666 for this path.
		wantMode = 0o666
	}
	if info.Mode().Perm() != wantMode {
		t.Errorf("index mode = %o, want %o", info.Mode().Perm(), wantMode)
	}
}
