//! Go-compatible public CLI artifacts. The data is generated by real immutable
//! Go, and the shell protocol executes here without a Go runtime dependency.
use serde::Deserialize;
use std::{collections::BTreeMap, sync::LazyLock};

#[derive(Deserialize)]
pub struct Artifacts {
    pub help: BTreeMap<String, String>,
    pub completions: BTreeMap<String, String>,
    pub manpages: BTreeMap<String, String>,
    pub config_keys: Vec<String>,
    pub commands: Vec<Command>,
}

#[derive(Deserialize)]
pub struct Command {
    pub path: String,
    pub name: String,
    pub short: String,
    pub aliases: Option<Vec<String>>,
    pub valid_args: Option<Vec<String>>,
    pub arg_aliases: Option<Vec<String>>,
    pub hidden: bool,
    pub deprecated: String,
    pub available: bool,
    pub disable_flag_parsing: bool,
    pub dynamic: String,
    pub local_flags: Vec<Flag>,
    pub persistent_flags: Vec<Flag>,
}

#[derive(Deserialize)]
pub struct Flag {
    pub name: String,
    pub shorthand: String,
    pub usage: String,
    #[serde(rename = "type")]
    pub kind: String,
    pub no_opt_default: String,
    pub hidden: bool,
    pub deprecated: String,
    pub annotations: Option<BTreeMap<String, Vec<String>>>,
}

pub static DATA: LazyLock<Artifacts> = LazyLock::new(|| {
    serde_json::from_str(include_str!("../../../testdata/port/cli/artifacts.json"))
        .expect("verified Go CLI artifact schema")
});

/// The generated description advertises the actual resolved config location.
/// Keep the environment-derived path live rather than embedding capture HOME.
pub fn render(text: &str) -> std::borrow::Cow<'_, str> {
    if text.contains("__CONFIG_PATH__") {
        std::borrow::Cow::Owned(
            text.replace(
                "__CONFIG_PATH__",
                &symvault_core::config::PathResolver::new()
                    .config_path()
                    .to_string_lossy(),
            ),
        )
    } else {
        std::borrow::Cow::Borrowed(text)
    }
}

pub fn root() -> &'static Command {
    DATA.commands
        .iter()
        .find(|c| c.path == "symvault")
        .expect("root artifact")
}

/// Go `strconv.Quote` for UTF-8 flag diagnostics. Duration errors intentionally
/// retain `time`'s different byte-oriented quoting in the core duration parser.
pub fn quote_go_string(value: &str) -> String {
    let mut quoted = String::with_capacity(value.len() + 2);
    quoted.push('"');
    for character in value.chars() {
        match character {
            '"' => quoted.push_str("\\\""),
            '\\' => quoted.push_str("\\\\"),
            '\u{7}' => quoted.push_str("\\a"),
            '\u{8}' => quoted.push_str("\\b"),
            '\u{c}' => quoted.push_str("\\f"),
            '\n' => quoted.push_str("\\n"),
            '\r' => quoted.push_str("\\r"),
            '\t' => quoted.push_str("\\t"),
            '\u{b}' => quoted.push_str("\\v"),
            character if symvault_platform::approval::go_is_print(character) => {
                quoted.push(character);
            }
            character => {
                let code = u32::from(character);
                if code < 0x80 {
                    quoted.push_str(&format!("\\x{code:02x}"));
                } else if code <= 0xffff {
                    quoted.push_str(&format!("\\u{code:04x}"));
                } else {
                    quoted.push_str(&format!("\\U{code:08x}"));
                }
            }
        }
    }
    quoted.push('"');
    quoted
}

pub fn children(command: &Command) -> impl Iterator<Item = &'static Command> {
    let prefix = format!("{} ", command.path);
    DATA.commands.iter().filter(move |c| {
        c.path
            .strip_prefix(&prefix)
            .is_some_and(|rest| !rest.contains(' '))
    })
}

pub fn child(command: &Command, name: &str) -> Option<&'static Command> {
    children(command).find(|c| {
        c.name == name
            || c.aliases
                .as_ref()
                .is_some_and(|a| a.iter().any(|a| a == name))
    })
}

pub fn flags(command: &'static Command) -> Vec<&'static Flag> {
    let mut inherited = BTreeMap::new();
    let mut scope = root().path.clone();
    for part in command.path.split(' ').skip(1) {
        if let Some(parent) = DATA.commands.iter().find(|c| c.path == scope) {
            for flag in &parent.persistent_flags {
                inherited.insert(flag.name.as_str(), flag);
            }
        }
        scope.push(' ');
        scope.push_str(part);
    }
    let mut local = BTreeMap::new();
    for flag in command.persistent_flags.iter().chain(&command.local_flags) {
        inherited.remove(flag.name.as_str());
        local.insert(flag.name.as_str(), flag);
    }
    inherited.into_values().chain(local.into_values()).collect()
}

pub fn flag(command: &'static Command, word: &str) -> Option<&'static Flag> {
    let word = word.split('=').next()?;
    if let Some(name) = word.strip_prefix("--") {
        flags(command).into_iter().find(|f| f.name == name)
    } else {
        let name = word.strip_prefix('-')?;
        flags(command)
            .into_iter()
            .find(|f| !f.shorthand.is_empty() && f.shorthand == name)
    }
}

/// Help parsing follows Cobra's flag values and separator. Invalid flags stay
/// in the ordinary parser path; a help flag cannot hide a malformed argument.
pub fn flag_help(args: &[std::ffi::OsString]) -> Option<&'static str> {
    if !args
        .iter()
        .any(|a| a == "--help" || a == "-h" || a.to_str().is_some_and(|s| s.starts_with("--help=")))
    {
        return None;
    }
    let mut selected = root();
    let mut seen = Vec::new();
    let mut help = false;
    let mut i = 1;
    while let Some(word) = args.get(i) {
        let word = word.to_str()?;
        if word == "--" {
            break;
        }
        if word.starts_with('-') {
            let f = flag(selected, word)?;
            let inline = word.split_once('=').map(|(_, v)| v);
            let value = if let Some(v) = inline {
                v
            } else if f.no_opt_default.is_empty() {
                i += 1;
                args.get(i)?.to_str()?
            } else {
                &f.no_opt_default
            };
            if f.kind == "bool" {
                let enabled = crate::intake_commands::parse_bool(value).ok()?;
                if f.name == "help" {
                    help = enabled;
                }
            } else if matches!(f.kind.as_str(), "int" | "int64" | "uint" | "uint64") {
                if f.kind.starts_with('u') {
                    value.parse::<u64>().ok()?;
                } else {
                    value.parse::<i64>().ok()?;
                }
            } else if f.kind == "duration" {
                symvault_core::config::parse_go_duration(value).ok()?;
            }
            seen.push(f.name.as_str());
        } else if let Some(next) = child(selected, word) {
            selected = next;
        }
        i += 1;
    }
    if !help
        || seen
            .iter()
            .any(|name| !flags(selected).iter().any(|f| f.name == *name))
    {
        return None;
    }
    DATA.help
        .contains_key(&selected.path)
        .then_some(selected.path.strip_prefix("symvault ").unwrap_or(""))
}
