package main

import (
	"bytes"
	"flag"
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"unicode"
)

type codeRange struct{ first, last uint32 }

func main() {
	write := flag.Bool("write", false, "write Go Unicode IsPrint ranges for Rust")
	flag.Parse()
	data := generate()
	path := filepath.Join("crates", "symvault-platform", "src", "go_unicode_print_15.rs")
	if *write {
		if err := os.WriteFile(path, data, 0o644); err != nil {
			fatal(err)
		}
		return
	}
	current, err := os.ReadFile(path)
	if err != nil {
		fatal(err)
	}
	if !bytes.Equal(current, data) {
		fatal(fmt.Errorf("Go IsPrint table is stale; regenerate with go run ./scripts/rust-port/cmd/secure_input_unicode -write"))
	}
}

func generate() []byte {
	var ranges []codeRange
	for code := uint32(0); code <= unicode.MaxRune; code++ {
		if code >= 0xd800 && code <= 0xdfff {
			continue
		}
		if unicode.IsPrint(rune(code)) {
			ranges = appendRange(ranges, code)
		}
	}
	var out strings.Builder
	out.WriteString("// Generated by scripts/rust-port/cmd/secure_input_unicode using Go Unicode ")
	out.WriteString(unicode.Version)
	out.WriteString(". Do not edit by hand.\n")
	out.WriteString("pub(super) const PRINT_RANGES: &[(u32, u32)] = &[\n")
	for _, item := range ranges {
		fmt.Fprintf(&out, "    (0x%x, 0x%x),\n", item.first, item.last)
	}
	out.WriteString("];\n")
	return []byte(out.String())
}

func appendRange(ranges []codeRange, code uint32) []codeRange {
	if len(ranges) > 0 && ranges[len(ranges)-1].last+1 == code {
		ranges[len(ranges)-1].last = code
		return ranges
	}
	return append(ranges, codeRange{code, code})
}

func fatal(err error) {
	fmt.Fprintln(os.Stderr, err)
	os.Exit(1)
}
