package intake

import (
	"crypto/rand"
	"encoding/hex"
	"fmt"
	"os"
	"path/filepath"
)

// Spool is a private staging directory for intake source copies. It is
// created with 0700 permissions; each staged copy is written with 0600 and
// verified by read-back hash before it is used, so a source that changes or
// vanishes mid-run never reaches the vault untrusted.
type Spool struct {
	dir string
}

// NewSpool creates (or reuses) a private spool directory below the system
// temp root. The caller owns cleanup via Remove.
func NewSpool() (*Spool, error) {
	dir, err := os.MkdirTemp("", "symvault-intake-")
	if err != nil {
		return nil, fmt.Errorf("create intake spool: %w", err)
	}
	// #nosec G302 -- 0700 is the correct mode for a private directory
	// (gosec's 0600 rule targets regular files).
	if err := os.Chmod(dir, 0o700); err != nil {
		_ = os.RemoveAll(dir)
		return nil, fmt.Errorf("secure intake spool: %w", err)
	}
	return &Spool{dir: dir}, nil
}

// Dir returns the spool root (for tests and diagnostics).
func (s *Spool) Dir() string { return s.dir }

// Remove deletes the spool directory and everything in it. Intake never
// deletes source files, only its own private staging copies.
func (s *Spool) Remove() {
	if s != nil && s.dir != "" {
		_ = os.RemoveAll(s.dir)
	}
}

// Stage validates the source, copies it atomically into the spool with 0600
// permissions, and verifies the staged bytes by read-back hash. It returns
// the staged copy path and full provenance.
func (s *Spool) Stage(sourcePath string, limit int64) (string, Provenance, error) {
	data, fi, err := readBounded(sourcePath, limit)
	if err != nil {
		return "", Provenance{}, err
	}
	sha := HashSHA256(data)

	name := filepath.Base(sourcePath)
	stageName, err := randomName()
	if err != nil {
		return "", Provenance{}, err
	}
	// Preserve the extension so downstream consumers can render/OCR the copy.
	dst := filepath.Join(s.dir, stageName+"-"+name)

	if writeErr := os.WriteFile(dst, data, 0o600); writeErr != nil {
		return "", Provenance{}, fmt.Errorf("stage %q: %w", sourcePath, writeErr)
	}

	// Verify the staged copy by read-back hash before returning.
	back, err := os.ReadFile(dst) // #nosec G304 -- staged copy path is generated by us
	if err != nil {
		return "", Provenance{}, fmt.Errorf("verify staged copy: %w", err)
	}
	if HashSHA256(back) != sha {
		return "", Provenance{}, fmt.Errorf("staged copy verification failed for %q", sourcePath)
	}

	return dst, Provenance{
		SourcePath: sourcePath,
		SourceName: name,
		SourceType: SourceFileType(name),
		Size:       fi.Size(),
		SHA256:     sha,
		MTime:      fi.ModTime(),
		SpoolPath:  dst,
	}, nil
}

func randomName() (string, error) {
	buf := make([]byte, 8)
	if _, err := rand.Read(buf); err != nil {
		return "", fmt.Errorf("generate spool name: %w", err)
	}
	return hex.EncodeToString(buf), nil
}
