use std::collections::BTreeMap;

/// Render the five built-in templates used by Go's `internal/template` package.
///
/// Custom templates and output files deliberately stay outside this portable
/// runtime: loading either would require ambient HOME or filesystem policy.
/// This function only renders masked values and never accesses a store.
pub(crate) fn render_builtin(
    template_type: &str,
    name: &str,
    refs: &BTreeMap<String, String>,
) -> Result<String, String> {
    let values = refs
        .keys()
        .map(|alias| (alias.clone(), "***".to_owned()))
        .collect::<BTreeMap<_, _>>();
    match template_type {
        "env" => Ok(render_env(refs, &values)),
        "docker-compose" => Ok(render_docker_compose(refs, &values)),
        "k8s-secret" => Ok(render_k8s_secret(name, refs, &values)),
        "github-actions" => Ok(render_github_actions(name, refs, &values)),
        "terraform" => render_terraform(name, refs, &values),
        other => Err(format!("template not found: {other}")),
    }
}

fn render_env(refs: &BTreeMap<String, String>, values: &BTreeMap<String, String>) -> String {
    let mut output = String::from("# Generated by Symaira Vault\n");
    for alias in refs.keys() {
        output.push_str("export ");
        output.push_str(alias);
        output.push('=');
        output.push_str(values.get(alias).map(String::as_str).unwrap_or_default());
        output.push('\n');
    }
    output
}

fn render_docker_compose(
    refs: &BTreeMap<String, String>,
    values: &BTreeMap<String, String>,
) -> String {
    let mut output = String::from("version: \"3.8\"\nservices:\n  app:\n    environment:\n");
    for alias in refs.keys() {
        output.push_str("      - ");
        output.push_str(alias);
        output.push('=');
        output.push_str(values.get(alias).map(String::as_str).unwrap_or_default());
        output.push('\n');
    }
    output.push_str("    secrets:\n");
    for alias in refs.keys() {
        output.push_str("      - ");
        output.push_str(&alias.to_lowercase());
        output.push_str("_secret\n");
    }
    output.push_str("secrets:\n");
    for alias in refs.keys() {
        let alias = alias.to_lowercase();
        output.push_str("  ");
        output.push_str(&alias);
        output.push_str("_secret:\n    file: ./secrets/");
        output.push_str(&alias);
        output.push_str(".txt\n");
    }
    output
}

fn render_k8s_secret(
    name: &str,
    refs: &BTreeMap<String, String>,
    values: &BTreeMap<String, String>,
) -> String {
    let mut output =
        format!("apiVersion: v1\nkind: Secret\nmetadata:\n  name: {name}\ntype: Opaque\ndata:\n");
    for alias in refs.keys() {
        output.push_str("  ");
        output.push_str(alias);
        output.push_str(": ");
        output.push_str(&base64_standard(
            values.get(alias).map(String::as_bytes).unwrap_or_default(),
        ));
        output.push('\n');
    }
    output
}

fn render_github_actions(
    name: &str,
    refs: &BTreeMap<String, String>,
    values: &BTreeMap<String, String>,
) -> String {
    let mut output = format!(
        "name: Deploy {name}\n\non:\n  push:\n    branches: [main]\n\njobs:\n  deploy:\n    runs-on: ubuntu-latest\n    steps:\n      - uses: actions/checkout@v4\n      - name: Configure secrets\n        env:\n"
    );
    for alias in refs.keys() {
        output.push_str("          ");
        output.push_str(alias);
        output.push_str(": ");
        output.push_str(values.get(alias).map(String::as_str).unwrap_or_default());
        output.push('\n');
    }
    output.push_str("        run: |\n          echo \"Secrets configured\"\n");
    output
}

fn render_terraform(
    name: &str,
    refs: &BTreeMap<String, String>,
    values: &BTreeMap<String, String>,
) -> Result<String, String> {
    let mut output = format!("# Terraform variables for {name}\n# Generated by Symaira Vault\n");
    for alias in refs.keys() {
        let value = values.get(alias).map(String::as_str).unwrap_or_default();
        let encoded = symvault_gojson::to_string(&value).map_err(|error| error.to_string())?;
        output.push_str("variable \"");
        output.push_str(&alias.to_lowercase());
        output.push_str("\" {\n  type      = string\n  sensitive = true\n  default   = ");
        output.push_str(&encoded);
        output.push_str("\n}\n");
    }
    Ok(output)
}

fn base64_standard(bytes: &[u8]) -> String {
    const ALPHABET: &[u8; 64] = b"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/";
    let mut output = String::with_capacity(bytes.len().div_ceil(3) * 4);
    for chunk in bytes.chunks(3) {
        let first = chunk[0];
        output.push(ALPHABET[(first >> 2) as usize] as char);
        let second = chunk.get(1).copied();
        output.push(
            ALPHABET[((first & 0x03) << 4 | second.map_or(0, |value| value >> 4)) as usize] as char,
        );
        match second {
            None => output.push_str("=="),
            Some(second) => {
                output.push(
                    ALPHABET[((second & 0x0f) << 2
                        | chunk.get(2).copied().map_or(0, |value| value >> 6))
                        as usize] as char,
                );
                match chunk.get(2).copied() {
                    None => output.push('='),
                    Some(third) => output.push(ALPHABET[(third & 0x3f) as usize] as char),
                }
            }
        }
    }
    output
}

#[cfg(test)]
mod tests {
    use super::base64_standard;

    #[test]
    fn base64_matches_standard_encoding() {
        assert_eq!(base64_standard(b""), "");
        assert_eq!(base64_standard(b"f"), "Zg==");
        assert_eq!(base64_standard(b"fo"), "Zm8=");
        assert_eq!(base64_standard(b"foo"), "Zm9v");
    }
}
