.nh
.TH "SYMAIRA" "1" "May 2026" "Symaira Vault" "OpenPass Manual"

.SH NAME
symaira-policy-apply - Apply a policy file to the vault


.SH SYNOPSIS
\fBsymaira policy apply  [flags]\fP


.SH DESCRIPTION
Load and validate a policy file, then copy it to the vault's policies directory.

.PP
Example:
  openpass policy apply ~/policies/dev.yaml


.SH OPTIONS
\fB-h\fP, \fB--help\fP[=false]
	help for apply


.SH OPTIONS INHERITED FROM PARENT COMMANDS
\fB--color\fP="auto"
	When to emit ANSI color: auto, always, never

.PP
\fB--no-pipe-warning\fP[=false]
	suppress 'reading from non-TTY' warning when piping secrets

.PP
\fB--output\fP="text"
	Output format (text, json, yaml)

.PP
\fB--profile\fP=""
	use a named vault profile

.PP
\fB--quiet\fP[=false]
	suppress non-error output

.PP
\fB--theme\fP=""
	Color preset: default, highcontrast, colorblind (or OPENPASS_THEME)

.PP
\fB--vault\fP="~/.openpass"
	path to the password vault


.SH SEE ALSO
\fBsymaira-policy(1)\fP
