.nh
.TH "SYMAIRA" "1" "Apr 2026" "Symaira Vault" "OpenPass Manual"

.SH NAME
symaira-add - Add a new password entry


.SH SYNOPSIS
\fBsymaira add  [flags]\fP


.SH DESCRIPTION
Creates a new password entry in the vault.

.PP
The entry name can use slash notation for organization (e.g., work/aws).
Interactive mode prompts for username, password, and URL.

.PP
Examples:
  openpass add github
  openpass add work/aws
  openpass add personal/bank
  openpass add github-token --value "my-secret-token"
  openpass add secure-pass --generate --length 20


.SH OPTIONS
\fB--force\fP[=false]
	Skip password strength validation

.PP
\fB--generate\fP[=false]
	Generate a secure password (non-interactive)

.PP
\fB-h\fP, \fB--help\fP[=false]
	help for add

.PP
\fB--length\fP=20
	Generated password length for --generate

.PP
\fB--notes\fP=""
	Notes (non-interactive)

.PP
\fB--totp-account\fP=""
	TOTP account name/username

.PP
\fB--totp-issuer\fP=""
	TOTP issuer/service name

.PP
\fB--totp-secret\fP=""
	TOTP secret key (base32 encoded)

.PP
\fB--url\fP=""
	URL (non-interactive)

.PP
\fB--username\fP=""
	Username (non-interactive)

.PP
\fB--value\fP=""
	Password value (non-interactive)


.SH OPTIONS INHERITED FROM PARENT COMMANDS
\fB--profile\fP=""
	use a named vault profile

.PP
\fB--quiet\fP[=false]
	suppress non-error output

.PP
\fB--vault\fP="~/.openpass"
	path to the password vault


.SH SEE ALSO
\fBopenpass(1)\fP
