.nh
.TH "SYMAIRA" "1" "Apr 2026" "Symaira Vault" "OpenPass Manual"

.SH NAME
symaira-get - Get a password entry


.SH SYNOPSIS
\fBsymaira get  [flags]\fP


.SH DESCRIPTION
Retrieves and displays a password entry. Use path.field syntax to get specific fields.


.SH OPTIONS
\fB-c\fP, \fB--clip\fP[=false]
	Copy value to clipboard

.PP
\fB-h\fP, \fB--help\fP[=false]
	help for get

.PP
\fB-j\fP, \fB--json\fP[=false]
	Output as JSON


.SH OPTIONS INHERITED FROM PARENT COMMANDS
\fB--profile\fP=""
	use a named vault profile

.PP
\fB--quiet\fP[=false]
	suppress non-error output

.PP
\fB--vault\fP="~/.openpass"
	path to the password vault


.SH SEE ALSO
\fBopenpass(1)\fP
