.nh
.TH "SYMAIRA" "1" "Apr 2026" "Symaira Vault" "OpenPass Manual"

.SH NAME
symaira-set - Set a password entry or field


.SH SYNOPSIS
\fBsymaira set  [--value value] [flags]\fP


.SH DESCRIPTION
Creates or updates a password entry. Use --value or interactive mode.


.SH OPTIONS
\fB--force\fP[=false]
	Skip password strength validation

.PP
\fB-h\fP, \fB--help\fP[=false]
	help for set

.PP
\fB--totp-account\fP=""
	TOTP account name/username

.PP
\fB--totp-issuer\fP=""
	TOTP issuer/service name

.PP
\fB--totp-secret\fP=""
	TOTP secret key (base32 encoded)

.PP
\fB--value\fP=""
	Value to set (skip interactive)


.SH OPTIONS INHERITED FROM PARENT COMMANDS
\fB--profile\fP=""
	use a named vault profile

.PP
\fB--quiet\fP[=false]
	suppress non-error output

.PP
\fB--vault\fP="~/.openpass"
	path to the password vault


.SH SEE ALSO
\fBopenpass(1)\fP
