.nh
.TH "SYMAIRA" "1" "May 2026" "Symaira Vault" "OpenPass Manual"

.SH NAME
symaira-device - Manage paired devices for multi-device vault access


.SH SYNOPSIS
\fBsymaira device [flags]\fP


.SH DESCRIPTION
Manage paired devices that can access this vault.

.PP
Use 'openpass device pair' to generate a pairing token for a new device,
and 'openpass device join' on the new device to join the vault.


.SH OPTIONS
\fB-h\fP, \fB--help\fP[=false]
	help for device


.SH OPTIONS INHERITED FROM PARENT COMMANDS
\fB--color\fP="auto"
	When to emit ANSI color: auto, always, never

.PP
\fB--no-pipe-warning\fP[=false]
	suppress 'reading from non-TTY' warning when piping secrets

.PP
\fB--output\fP="text"
	Output format (text, json, yaml)

.PP
\fB--profile\fP=""
	use a named vault profile

.PP
\fB--quiet\fP[=false]
	suppress non-error output

.PP
\fB--theme\fP=""
	Color preset: default, highcontrast, colorblind (or OPENPASS_THEME)

.PP
\fB--vault\fP="~/.openpass"
	path to the password vault


.SH EXAMPLE
.EX
  openpass device pair
  openpass device join ssh://user@host/path/to/vault.git <token>
  openpass device accept <token>
.EE


.SH SEE ALSO
\fBopenpass(1)\fP, \fBsymaira-device-accept(1)\fP, \fBsymaira-device-add(1)\fP, \fBsymaira-device-join(1)\fP, \fBsymaira-device-list(1)\fP, \fBsymaira-device-pair(1)\fP, \fBsymaira-device-revoke(1)\fP
