.nh
.TH "SYMAIRA" "1" "Apr 2026" "Symaira Vault" "OpenPass Manual"

.SH NAME
symaira-auth-set - Set the vault unlock authentication method


.SH SYNOPSIS
\fBsymaira auth set passphrase|touchid [flags]\fP


.SH DESCRIPTION
Set the vault unlock authentication method


.SH OPTIONS
\fB-h\fP, \fB--help\fP[=false]
	help for set


.SH OPTIONS INHERITED FROM PARENT COMMANDS
\fB--profile\fP=""
	use a named vault profile

.PP
\fB--quiet\fP[=false]
	suppress non-error output

.PP
\fB--vault\fP="~/.openpass"
	path to the password vault


.SH SEE ALSO
\fBsymaira-auth(1)\fP
