.nh
.TH "SYMAIRA" "1" "May 2026" "Symaira Vault" "OpenPass Manual"

.SH NAME
symaira-agent-profile-export - Export agent profile as YAML


.SH SYNOPSIS
\fBsymaira agent profile export [flags]\fP


.SH DESCRIPTION
Export the agent profile to stdout or to a file.
Output is in YAML format by default.


.SH OPTIONS
\fB-h\fP, \fB--help\fP[=false]
	help for export

.PP
\fB-o\fP, \fB--output\fP=""
	Output file path (default: stdout)


.SH OPTIONS INHERITED FROM PARENT COMMANDS
\fB--color\fP="auto"
	When to emit ANSI color: auto, always, never

.PP
\fB--no-pipe-warning\fP[=false]
	suppress 'reading from non-TTY' warning when piping secrets

.PP
\fB--profile\fP=""
	use a named vault profile

.PP
\fB--quiet\fP[=false]
	suppress non-error output

.PP
\fB--theme\fP=""
	Color preset: default, highcontrast, colorblind (or OPENPASS_THEME)

.PP
\fB--vault\fP="~/.openpass"
	path to the password vault


.SH SEE ALSO
\fBsymaira-agent-profile(1)\fP
