.nh
.TH "SYMAIRA" "1" "Apr 2026" "Symaira Vault" "OpenPass Manual"

.SH NAME
symaira-version - Print the version of OpenPass


.SH SYNOPSIS
\fBsymaira version [flags]\fP


.SH DESCRIPTION
Print the version of OpenPass


.SH OPTIONS
\fB-h\fP, \fB--help\fP[=false]
	help for version


.SH OPTIONS INHERITED FROM PARENT COMMANDS
\fB--profile\fP=""
	use a named vault profile

.PP
\fB--quiet\fP[=false]
	suppress non-error output

.PP
\fB--vault\fP="~/.openpass"
	path to the password vault


.SH SEE ALSO
\fBopenpass(1)\fP
