.nh
.TH "SYMAIRA" "1" "Apr 2026" "Symaira Vault" "OpenPass Manual"

.SH NAME
symaira-generate-manpages - Generate manual pages


.SH SYNOPSIS
\fBsymaira generate manpages  [flags]\fP


.SH DESCRIPTION
Generate manual pages


.SH OPTIONS
\fB-h\fP, \fB--help\fP[=false]
	help for manpages


.SH OPTIONS INHERITED FROM PARENT COMMANDS
\fB--profile\fP=""
	use a named vault profile

.PP
\fB--quiet\fP[=false]
	suppress non-error output

.PP
\fB--vault\fP="~/.openpass"
	path to the password vault


.SH SEE ALSO
\fBsymaira-generate(1)\fP
