.nh
.TH "SYMAIRA" "1" "Apr 2026" "Symaira Vault" "OpenPass Manual"

.SH NAME
symaira-profile-use - Set the default profile


.SH SYNOPSIS
\fBsymaira profile use  [flags]\fP


.SH DESCRIPTION
Set the default profile to use when no --vault or OPENPASS_VAULT is specified.

.PP
Example:
  openpass profile use work


.SH OPTIONS
\fB-h\fP, \fB--help\fP[=false]
	help for use


.SH OPTIONS INHERITED FROM PARENT COMMANDS
\fB--profile\fP=""
	use a named vault profile

.PP
\fB--quiet\fP[=false]
	suppress non-error output

.PP
\fB--vault\fP="~/.openpass"
	path to the password vault


.SH SEE ALSO
\fBsymaira-profile(1)\fP
