.nh
.TH "SYMAIRA" "1" "Apr 2026" "Symaira Vault" "OpenPass Manual"

.SH NAME
symaira-import - Import entries from another password manager


.SH SYNOPSIS
\fBsymaira import   [flags]\fP


.SH DESCRIPTION
Imports password entries from 1Password, Bitwarden, pass, or CSV exports.


.SH OPTIONS
\fB--dry-run\fP[=false]
	Parse import source without writing entries

.PP
\fB-h\fP, \fB--help\fP[=false]
	help for import

.PP
\fB--mapping\fP=""
	CSV column mapping (format: title=col1,username=col2,...)

.PP
\fB--overwrite\fP[=false]
	Delete existing entries before writing

.PP
\fB--prefix\fP=""
	Prepend path to all imported entries

.PP
\fB--skip-existing\fP[=false]
	Skip entries that already exist


.SH OPTIONS INHERITED FROM PARENT COMMANDS
\fB--profile\fP=""
	use a named vault profile

.PP
\fB--quiet\fP[=false]
	suppress non-error output

.PP
\fB--vault\fP="~/.openpass"
	path to the password vault


.SH SEE ALSO
\fBopenpass(1)\fP
