.nh
.TH "SYMAIRA" "1" "Apr 2026" "Symaira Vault" "OpenPass Manual"

.SH NAME
symaira-edit - Edit an existing password entry


.SH SYNOPSIS
\fBsymaira edit  [flags]\fP


.SH DESCRIPTION
Opens an existing password entry in your default editor for modification.

.PP
The entry is opened in JSON format. Save and exit the editor to update the entry.
If the entry does not exist, an error is returned.

.PP
The editor is determined by the --editor flag or EDITOR environment variable (defaults to vi).

.EX
Examples:
.EE

.PP
symaira edit github
  openpass edit work/aws
  openpass edit personal/bank --editor nano
  EDITOR=nano openpass edit personal/bank


.SH OPTIONS
\fB--editor\fP=""
	Editor to use (overrides EDITOR env var)

.PP
\fB-h\fP, \fB--help\fP[=false]
	help for edit


.SH OPTIONS INHERITED FROM PARENT COMMANDS
\fB--profile\fP=""
	use a named vault profile

.PP
\fB--quiet\fP[=false]
	suppress non-error output

.PP
\fB--vault\fP="~/.openpass"
	path to the password vault


.SH SEE ALSO
\fBopenpass(1)\fP
