.nh
.TH "SYMAIRA" "1" "May 2026" "Symaira Vault" "OpenPass Manual"

.SH NAME
symaira-device-accept - Accept a join request and re-encrypt entries for the new device


.SH SYNOPSIS
\fBsymaira device accept  [flags]\fP


.SH DESCRIPTION
Accept a device join request by adding the new device's public key
as a recipient and re-encrypting all vault entries so the new device
can decrypt them.


.SH OPTIONS
\fB-h\fP, \fB--help\fP[=false]
	help for accept


.SH OPTIONS INHERITED FROM PARENT COMMANDS
\fB--color\fP="auto"
	When to emit ANSI color: auto, always, never

.PP
\fB--no-pipe-warning\fP[=false]
	suppress 'reading from non-TTY' warning when piping secrets

.PP
\fB--output\fP="text"
	Output format (text, json, yaml)

.PP
\fB--profile\fP=""
	use a named vault profile

.PP
\fB--quiet\fP[=false]
	suppress non-error output

.PP
\fB--theme\fP=""
	Color preset: default, highcontrast, colorblind (or OPENPASS_THEME)

.PP
\fB--vault\fP="~/.openpass"
	path to the password vault


.SH EXAMPLE
.EX
  openpass device accept 123456
.EE


.SH SEE ALSO
\fBsymaira-device(1)\fP
