.nh
.TH "SYMAIRA" "1" "Apr 2026" "Symaira Vault" "OpenPass Manual"

.SH NAME
symaira-lock - Lock the vault (clear session)


.SH SYNOPSIS
\fBsymaira lock [flags]\fP


.SH DESCRIPTION
Lock the vault (clear session)


.SH OPTIONS
\fB-h\fP, \fB--help\fP[=false]
	help for lock


.SH OPTIONS INHERITED FROM PARENT COMMANDS
\fB--profile\fP=""
	use a named vault profile

.PP
\fB--quiet\fP[=false]
	suppress non-error output

.PP
\fB--vault\fP="~/.openpass"
	path to the password vault


.SH SEE ALSO
\fBopenpass(1)\fP
