.nh
.TH "SYMAIRA" "1" "May 2026" "Symaira Vault" "OpenPass Manual"

.SH NAME
symaira-share-revoke - Revoke a share grant


.SH SYNOPSIS
\fBsymaira share revoke  [flags]\fP


.SH DESCRIPTION
Revoke an active share grant, immediately removing the recipient's access to the shared secret.


.SH OPTIONS
\fB-h\fP, \fB--help\fP[=false]
	help for revoke


.SH OPTIONS INHERITED FROM PARENT COMMANDS
\fB--color\fP="auto"
	When to emit ANSI color: auto, always, never

.PP
\fB--no-pipe-warning\fP[=false]
	suppress 'reading from non-TTY' warning when piping secrets

.PP
\fB--output\fP="text"
	Output format (text, json, yaml)

.PP
\fB--profile\fP=""
	use a named vault profile

.PP
\fB--quiet\fP[=false]
	suppress non-error output

.PP
\fB--theme\fP=""
	Color preset: default, highcontrast, colorblind (or OPENPASS_THEME)

.PP
\fB--vault\fP="~/.openpass"
	path to the password vault


.SH SEE ALSO
\fBsymaira-share(1)\fP
