.nh
.TH "SYMAIRA" "1" "Apr 2026" "Symaira Vault" "OpenPass Manual"

.SH NAME
symaira-init - Initialize a new password vault


.SH SYNOPSIS
\fBsymaira init [vault-dir] [flags]\fP


.SH DESCRIPTION
Creates a new vault directory with identity and configuration.


.SH OPTIONS
\fB--auth\fP="ask"
	unlock method for this vault (ask, passphrase, touchid)

.PP
\fB-h\fP, \fB--help\fP[=false]
	help for init


.SH OPTIONS INHERITED FROM PARENT COMMANDS
\fB--profile\fP=""
	use a named vault profile

.PP
\fB--quiet\fP[=false]
	suppress non-error output

.PP
\fB--vault\fP="~/.openpass"
	path to the password vault


.SH SEE ALSO
\fBopenpass(1)\fP
