.nh
.TH "SYMAIRA" "1" "Apr 2026" "Symaira Vault" "OpenPass Manual"

.SH NAME
symaira-completion-fish - Generate the autocompletion script for fish


.SH SYNOPSIS
\fBsymaira completion fish [flags]\fP


.SH DESCRIPTION
Generate the autocompletion script for the fish shell.

.PP
To load completions in your current shell session:

.EX
symaira completion fish | source
.EE

.PP
To load completions for every new session, execute once:

.EX
symaira completion fish > ~/.config/fish/completions/symvault.fish
.EE

.PP
You will need to start a new shell for this setup to take effect.


.SH OPTIONS
\fB-h\fP, \fB--help\fP[=false]
	help for fish

.PP
\fB--no-descriptions\fP[=false]
	disable completion descriptions


.SH OPTIONS INHERITED FROM PARENT COMMANDS
\fB--profile\fP=""
	use a named vault profile

.PP
\fB--quiet\fP[=false]
	suppress non-error output

.PP
\fB--vault\fP="~/.openpass"
	path to the password vault


.SH SEE ALSO
\fBsymaira-completion(1)\fP
