.nh
.TH "SYMAIRA" "1" "Apr 2026" "Symaira Vault" "OpenPass Manual"

.SH NAME
symaira - OpenPass is a Go CLI password manager


.SH SYNOPSIS
\fBsymaira [flags]\fP


.SH DESCRIPTION
OpenPass is a Go CLI password manager


.SH OPTIONS
\fB-h\fP, \fB--help\fP[=false]
	help for openpass

.PP
\fB--profile\fP=""
	use a named vault profile

.PP
\fB--quiet\fP[=false]
	suppress non-error output

.PP
\fB--vault\fP="~/.openpass"
	path to the password vault


.SH SEE ALSO
\fBsymaira-add(1)\fP, \fBsymaira-audit(1)\fP, \fBsymaira-auth(1)\fP, \fBsymaira-backup(1)\fP, \fBsymaira-completion(1)\fP, \fBsymaira-config(1)\fP, \fBsymaira-delete(1)\fP, \fBsymaira-diag(1)\fP, \fBsymaira-edit(1)\fP, \fBsymaira-find(1)\fP, \fBsymaira-generate(1)\fP, \fBsymaira-get(1)\fP, \fBsymaira-git(1)\fP, \fBsymaira-import(1)\fP, \fBsymaira-init(1)\fP, \fBsymaira-list(1)\fP, \fBsymaira-lock(1)\fP, \fBsymaira-mcp-config(1)\fP, \fBsymaira-mcp-token-rotate(1)\fP, \fBsymaira-profile(1)\fP, \fBsymaira-recipients(1)\fP, \fBsymaira-restore(1)\fP, \fBsymaira-serve(1)\fP, \fBsymaira-set(1)\fP, \fBsymaira-ui(1)\fP, \fBsymaira-unlock(1)\fP, \fBsymaira-update(1)\fP, \fBsymaira-version(1)\fP
