.nh
.TH "SYMAIRA" "1" "Apr 2026" "Symaira Vault" "OpenPass Manual"

.SH NAME
symaira-recipients-remove - Remove a recipient


.SH SYNOPSIS
\fBsymaira recipients remove  [flags]\fP


.SH DESCRIPTION
Remove a recipient (public key) from the vault.

.PP
The public key must match exactly. Use 'openpass recipients list' to see current recipients.

.PP
Use --yes to skip confirmation (useful for scripts).

.PP
Example:
  openpass recipients remove age1ql3z7hjy54pw3hyww5ayyfg7zqgvc7w3j2elw8zmrj2kg5sfn9aqmcac8p


.SH OPTIONS
\fB-h\fP, \fB--help\fP[=false]
	help for remove

.PP
\fB-y\fP, \fB--yes\fP[=false]
	Skip confirmation prompt


.SH OPTIONS INHERITED FROM PARENT COMMANDS
\fB--profile\fP=""
	use a named vault profile

.PP
\fB--quiet\fP[=false]
	suppress non-error output

.PP
\fB--vault\fP="~/.openpass"
	path to the password vault


.SH SEE ALSO
\fBsymaira-recipients(1)\fP
