.nh
.TH "SYMAIRA" "1" "Apr 2026" "Symaira Vault" "OpenPass Manual"

.SH NAME
symaira-recipients - Manage vault recipients for multi-user encryption


.SH SYNOPSIS
\fBsymaira recipients [flags]\fP


.SH DESCRIPTION
Manage recipients (public keys) that can decrypt vault entries.

.PP
Recipients are stored in recipients.txt in the vault directory.
Each line contains one public key in age format (starting with "age1").
Lines starting with # are treated as comments.

.PP
Examples:
  openpass recipients list              # List all recipients
  openpass recipients add age1...       # Add a new recipient
  openpass recipients remove age1...    # Remove a recipient


.SH OPTIONS
\fB-h\fP, \fB--help\fP[=false]
	help for recipients


.SH OPTIONS INHERITED FROM PARENT COMMANDS
\fB--profile\fP=""
	use a named vault profile

.PP
\fB--quiet\fP[=false]
	suppress non-error output

.PP
\fB--vault\fP="~/.openpass"
	path to the password vault


.SH SEE ALSO
\fBopenpass(1)\fP, \fBsymaira-recipients-add(1)\fP, \fBsymaira-recipients-list(1)\fP, \fBsymaira-recipients-remove(1)\fP
