.nh
.TH "SYMVAULT" "1" "Sep 2026" "Symaira Vault" "Symaira Vault Manual"

.SH NAME
symvault-update-check - Check GitHub for a newer Symaira Vault release


.SH SYNOPSIS
\fBsymvault update check [flags]\fP


.SH DESCRIPTION
Check GitHub for a newer Symaira Vault release


.SH OPTIONS
\fB--force\fP[=false]
	bypass cache and force a fresh check

.PP
\fB-h\fP, \fB--help\fP[=false]
	help for check

.PP
\fB--json\fP[=false]
	output update check result as JSON (deprecated: use --output=json)

.PP
\fB--quiet\fP[=false]
	suppress non-essential output (exit code 1 if update available)


.SH OPTIONS INHERITED FROM PARENT COMMANDS
\fB--color\fP="auto"
	When to emit ANSI color: auto, always, never

.PP
\fB--no-pipe-warning\fP[=false]
	suppress 'reading from non-TTY' warning when piping secrets

.PP
\fB--output\fP="text"
	Output format (text, json, yaml)

.PP
\fB--profile\fP=""
	use a named vault profile

.PP
\fB--theme\fP=""
	Color preset: default, highcontrast, colorblind (or SYMVAULT_THEME)

.PP
\fB--vault\fP="~/.symvault"
	path to the password vault


.SH SEE ALSO
\fBsymvault-update(1)\fP
