.nh
.TH "SYMVAULT" "1" "Aug 2026" "Symaira Vault" "Symaira Vault Manual"

.SH NAME
symvault-device-list - List all devices


.SH SYNOPSIS
\fBsymvault device list [flags]\fP


.SH DESCRIPTION
List all devices registered in the vault's device registry.

.PP
Shows device name, public key (truncated), added date, and last seen time.
Also shows recipients from recipients.txt that are not associated with
any registered device (unmanaged recipients).


.SH OPTIONS
\fB-h\fP, \fB--help\fP[=false]
	help for list


.SH OPTIONS INHERITED FROM PARENT COMMANDS
\fB--color\fP="auto"
	When to emit ANSI color: auto, always, never

.PP
\fB--no-pipe-warning\fP[=false]
	suppress 'reading from non-TTY' warning when piping secrets

.PP
\fB--output\fP="text"
	Output format (text, json, yaml)

.PP
\fB--profile\fP=""
	use a named vault profile

.PP
\fB--quiet\fP[=false]
	suppress non-error output

.PP
\fB--theme\fP=""
	Color preset: default, highcontrast, colorblind (or SYMVAULT_THEME)

.PP
\fB--vault\fP="~/.symvault"
	path to the password vault


.SH EXAMPLE
.EX
  symvault device list
  symvault device list --output json
.EE


.SH SEE ALSO
\fBsymvault-device(1)\fP
