.nh
.TH "SYMVAULT" "1" "Aug 2026" "Symaira Vault" "Symaira Vault Manual"

.SH NAME
symvault-policy-apply - Apply a policy file to the vault


.SH SYNOPSIS
\fBsymvault policy apply  [flags]\fP


.SH DESCRIPTION
Load and validate a policy file, then copy it to the vault's policies directory.

.PP
Example:
  symvault policy apply ~/policies/dev.yaml


.SH OPTIONS
\fB-h\fP, \fB--help\fP[=false]
	help for apply


.SH OPTIONS INHERITED FROM PARENT COMMANDS
\fB--color\fP="auto"
	When to emit ANSI color: auto, always, never

.PP
\fB--no-pipe-warning\fP[=false]
	suppress 'reading from non-TTY' warning when piping secrets

.PP
\fB--output\fP="text"
	Output format (text, json, yaml)

.PP
\fB--profile\fP=""
	use a named vault profile

.PP
\fB--quiet\fP[=false]
	suppress non-error output

.PP
\fB--theme\fP=""
	Color preset: default, highcontrast, colorblind (or SYMVAULT_THEME)

.PP
\fB--vault\fP="~/.symvault"
	path to the password vault


.SH SEE ALSO
\fBsymvault-policy(1)\fP
