.nh
.TH "SYMVAULT" "1" "Sep 2026" "Symaira Vault" "Symaira Vault Manual"

.SH NAME
symvault-dynamic - Generate dynamic secrets with time-limited leases


.SH SYNOPSIS
\fBsymvault dynamic [flags]\fP


.SH DESCRIPTION
Generate dynamic secrets with time-limited leases for various backends.

.PP
Supported engines:
  postgres  - Create temporary PostgreSQL users with GRANT role
  aws-sts   - Generate temporary AWS STS credentials via AssumeRole


.SH OPTIONS
\fB-h\fP, \fB--help\fP[=false]
	help for dynamic


.SH OPTIONS INHERITED FROM PARENT COMMANDS
\fB--color\fP="auto"
	When to emit ANSI color: auto, always, never

.PP
\fB--json\fP[=false]
	Output format shorthand for --output json; overrides --output when both are specified

.PP
\fB--no-pipe-warning\fP[=false]
	suppress 'reading from non-TTY' warning when piping secrets

.PP
\fB--output\fP="text"
	Output format (text, json, yaml)

.PP
\fB--profile\fP=""
	use a named vault profile

.PP
\fB--quiet\fP[=false]
	suppress non-error output

.PP
\fB--theme\fP=""
	Color preset: default, highcontrast, colorblind (or SYMVAULT_THEME)

.PP
\fB--vault\fP="~/.symvault"
	path to the password vault


.SH EXAMPLE
.EX
  # Generate temporary PostgreSQL credentials valid for 1h
  symvault dynamic generate postgres --role analyst --ttl 1h

  # Short-lived AWS STS session
  symvault dynamic generate aws-sts --role arn:aws:iam::123:role/dev --ttl 15m
.EE


.SH SEE ALSO
\fBsymvault(1)\fP, \fBsymvault-dynamic-generate(1)\fP
