.nh
.TH "SYMVAULT" "1" "Aug 2026" "Symaira Vault" "Symaira Vault Manual"

.SH NAME
symvault-update - Check for Symaira Vault updates


.SH SYNOPSIS
\fBsymvault update [flags]\fP


.SH DESCRIPTION
Check for Symaira Vault updates


.SH OPTIONS
\fB-h\fP, \fB--help\fP[=false]
	help for update


.SH OPTIONS INHERITED FROM PARENT COMMANDS
\fB--color\fP="auto"
	When to emit ANSI color: auto, always, never

.PP
\fB--no-pipe-warning\fP[=false]
	suppress 'reading from non-TTY' warning when piping secrets

.PP
\fB--output\fP="text"
	Output format (text, json, yaml)

.PP
\fB--profile\fP=""
	use a named vault profile

.PP
\fB--quiet\fP[=false]
	suppress non-error output

.PP
\fB--theme\fP=""
	Color preset: default, highcontrast, colorblind (or SYMVAULT_THEME)

.PP
\fB--vault\fP="~/.symvault"
	path to the password vault


.SH EXAMPLE
.EX
  symvault update check
.EE


.SH SEE ALSO
\fBsymvault(1)\fP, \fBsymvault-update-apply(1)\fP, \fBsymvault-update-check(1)\fP, \fBsymvault-update-info(1)\fP
