.nh
.TH "SYMVAULT" "1" "Aug 2026" "Symaira Vault" "Symaira Vault Manual"

.SH NAME
symvault-remote-status - Show remote sync configuration


.SH SYNOPSIS
\fBsymvault remote status [flags]\fP


.SH DESCRIPTION
Display the current git remote configuration and sync status for the vault.


.SH OPTIONS
\fB-h\fP, \fB--help\fP[=false]
	help for status


.SH OPTIONS INHERITED FROM PARENT COMMANDS
\fB--color\fP="auto"
	When to emit ANSI color: auto, always, never

.PP
\fB--no-pipe-warning\fP[=false]
	suppress 'reading from non-TTY' warning when piping secrets

.PP
\fB--output\fP="text"
	Output format (text, json, yaml)

.PP
\fB--profile\fP=""
	use a named vault profile

.PP
\fB--quiet\fP[=false]
	suppress non-error output

.PP
\fB--theme\fP=""
	Color preset: default, highcontrast, colorblind (or SYMVAULT_THEME)

.PP
\fB--vault\fP="~/.symvault"
	path to the password vault


.SH SEE ALSO
\fBsymvault-remote(1)\fP
