// Command execute_secret_unicode verifies Go-compatible Unicode tables.
package main

import (
	"bytes"
	"flag"
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"unicode"
)

type pair struct{ first, second uint32 }

func main() {
	write := flag.Bool("write", false, "write generated Rust Unicode tables")
	flag.Parse()
	data := generate()
	path := filepath.Join("crates", "symvault-mcp", "src", "go_unicode_15.rs")
	if *write {
		if err := os.WriteFile(path, data, 0o644); err != nil {
			fatal(err)
		}
		return
	}
	current, err := os.ReadFile(path)
	if err != nil {
		fatal(err)
	}
	if !bytes.Equal(current, data) {
		fatal(fmt.Errorf("go Unicode 15 table is stale; regenerate with go run ./scripts/rust-port/cmd/execute_secret_unicode -write"))
	}
}

func generate() []byte {
	var upper, letters, digits []pair
	for code := uint32(0); code <= unicode.MaxRune; code++ {
		if code >= 0xd800 && code <= 0xdfff {
			continue
		}
		r := rune(code)
		mapped := uint32(unicode.ToUpper(r))
		if mapped != code {
			upper = append(upper, pair{code, mapped})
		}
		if unicode.IsLetter(r) {
			letters = appendRange(letters, code)
		}
		if unicode.IsDigit(r) {
			digits = appendRange(digits, code)
		}
	}
	var out strings.Builder
	out.WriteString("// Generated by scripts/rust-port/cmd/execute_secret_unicode using Go Unicode ")
	out.WriteString(unicode.Version)
	out.WriteString(". Do not edit by hand.\n")
	writePairs(&out, "SIMPLE_UPPER", upper)
	writePairs(&out, "LETTER_RANGES", letters)
	writePairs(&out, "DECIMAL_DIGIT_RANGES", digits)
	return []byte(out.String())
}

func appendRange(ranges []pair, code uint32) []pair {
	if len(ranges) > 0 && ranges[len(ranges)-1].second+1 == code {
		ranges[len(ranges)-1].second = code
		return ranges
	}
	return append(ranges, pair{code, code})
}

func writePairs(out *strings.Builder, name string, values []pair) {
	out.WriteString("pub(super) const ")
	out.WriteString(name)
	out.WriteString(": &[(u32, u32)] = &[\n")
	for _, item := range values {
		fmt.Fprintf(out, "    (0x%x, 0x%x),\n", item.first, item.second)
	}
	out.WriteString("];\n")
}

func fatal(err error) {
	fmt.Fprintln(os.Stderr, err)
	os.Exit(1)
}
