// Command storemetagen generates the deterministic entry metadata port fixture
// from the production Go preparation helper.
package main

import (
	"crypto/sha256"
	"encoding/hex"
	"encoding/json"
	"errors"
	"flag"
	"fmt"
	"os"
	"path/filepath"
	"runtime"
	"time"

	vault "github.com/danieljustus/symaira-vault/internal/vault"
)

const fixedNow = "2026-09-08T10:11:12.123456789Z"

var sourceFiles = []string{
	"internal/vault/entry.go",
	"internal/vault/entry_readwrite.go",
	"internal/vault/recipients.go",
	"internal/vault/entry_metadata.go",
}
var generatorFiles = []string{"scripts/rust-port/cmd/storemetagen/main.go"}

type oracle struct {
	Commit          string   `json:"commit"`
	Release         string   `json:"release"`
	SourceFiles     []string `json:"source_files"`
	SourceDigest    string   `json:"source_digest"`
	GeneratorFiles  []string `json:"generator_files"`
	GeneratorDigest string   `json:"generator_digest"`
}
type vector struct {
	Name         string          `json:"name"`
	Input        vault.Entry     `json:"input"`
	Path         string          `json:"path"`
	Pseudonymize bool            `json:"pseudonymize"`
	Now          string          `json:"now"`
	Expected     json.RawMessage `json:"expected"`
	ExpectedJSON string          `json:"expected_json"`
}
type fixture struct {
	SchemaVersion int      `json:"schema_version"`
	Oracle        oracle   `json:"oracle"`
	Vectors       []vector `json:"vectors"`
}

func repoRoot() (string, error) {
	_, file, _, ok := runtime.Caller(0)
	if !ok {
		return "", errors.New("locate generator")
	}
	return filepath.Clean(filepath.Join(filepath.Dir(file), "../../../../")), nil
}
func digest(root string, files []string) (string, error) {
	h := sha256.New()
	for _, name := range files {
		data, err := os.ReadFile(filepath.Join(root, name))
		if err != nil {
			return "", fmt.Errorf("read %s: %w", name, err)
		}
		fmt.Fprintf(h, "%s\x00", name)
		h.Write(data)
	}
	return hex.EncodeToString(h.Sum(nil)), nil
}
func makeFixture(root, commit, release string) (fixture, error) {
	if commit == "" || release == "" {
		return fixture{}, errors.New("oracle commit and release are required")
	}
	sourceDigest, err := digest(root, sourceFiles)
	if err != nil {
		return fixture{}, err
	}
	generatorDigest, err := digest(root, generatorFiles)
	if err != nil {
		return fixture{}, err
	}
	now, err := time.Parse(time.RFC3339Nano, fixedNow)
	if err != nil {
		return fixture{}, err
	}
	input := vault.Entry{Data: map[string]any{"token": "fixture-token"}, PendingWrite: &vault.WriteRecord{Field: "token", Action: "set"}}
	zero := vault.Entry{Data: nil, Metadata: vault.EntryMetadata{Version: 7}}
	existing := vault.Entry{Path: "old", Data: map[string]any{"x": "y"}, Metadata: vault.EntryMetadata{Created: now.Add(-time.Hour), Version: 2}}
	cases := []struct {
		name, path string
		pseudo     bool
		input      vault.Entry
	}{
		{"created_zero_pending", "logical/secret", true, input},
		{"nil_data_existing_version", "logical/empty", false, zero},
		{"created_nonzero", "logical/existing", true, existing},
	}
	vectors := make([]vector, 0, len(cases))
	for _, item := range cases {
		prepared := vault.PrepareEntryForWrite(&item.input, now, item.path, item.pseudo)
		raw, err := json.Marshal(prepared)
		if err != nil {
			return fixture{}, err
		}
		vectors = append(vectors, vector{item.name, item.input, item.path, item.pseudo, fixedNow, raw, string(raw)})
	}
	return fixture{1, oracle{commit, release, sourceFiles, sourceDigest, generatorFiles, generatorDigest}, vectors}, nil
}
func write(path string, value fixture) error {
	data, err := json.MarshalIndent(value, "", "  ")
	if err != nil {
		return err
	}
	data = append(data, '\n')
	if err := os.MkdirAll(filepath.Dir(path), 0o750); err != nil {
		return err
	}
	return os.WriteFile(path, data, 0o600)
}
func main() {
	output := flag.String("output", "testdata/port/store/metadata.json", "fixture path")
	commit := flag.String("oracle-commit", "", "Go oracle commit")
	release := flag.String("oracle-release", "", "Go oracle release")
	check := flag.Bool("check", false, "compare generated bytes with output")
	flag.Parse()
	root, err := repoRoot()
	if err != nil {
		fatal(err)
	}
	value, err := makeFixture(root, *commit, *release)
	if err != nil {
		fatal(err)
	}
	data, err := json.MarshalIndent(value, "", "  ")
	if err != nil {
		fatal(err)
	}
	data = append(data, '\n')
	if *check {
		actual, readErr := os.ReadFile(*output)
		if readErr != nil {
			fatal(readErr)
		}
		if string(actual) != string(data) {
			fatal(errors.New("metadata fixture is stale; regenerate it"))
		}
		fmt.Printf("PASS metadata fixture (%d vectors)\n", len(value.Vectors))
		return
	}
	if err := write(*output, value); err != nil {
		fatal(err)
	}
	fmt.Println("WROTE", *output)
}
func fatal(err error) { fmt.Fprintln(os.Stderr, "FAIL store metadata fixture:", err); os.Exit(1) }
